package killdoctorlucky.controller;

import static org.junit.Assert.assertEquals;

import java.io.StringReader;
import killdoctorlucky.model.RandomGenerator;
import killdoctorlucky.model.killdoctorlucky.KillDoctorLucky;
import killdoctorlucky.model.killdoctorlucky.KillDoctorLuckyMockModel;
import org.junit.Before;
import org.junit.Test;

/**
 * Test for KillDoctorLuckyConsoleController.
 */
public class KillDoctorLuckyConsoleControllerTest {

  private KillDoctorLucky killDoctorLucky;
  private StringReader input;
  private StringBuffer output;
  private RandomGenerator rg;
  private StringBuffer stringBuffer;
  private KillDoctorLuckyController killDoctorLuckyController;

  /**
   * Setup method for all of the tests.
   *
   */
  @Before
  public void setUp() {
    output = new StringBuffer();
    killDoctorLucky = new KillDoctorLuckyMockModel(output);
    stringBuffer = new StringBuffer();

  }

  @Test
  public void testFileNotFound() {
    input = new StringReader("q");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification1.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals("Specification file not found.\n", output.toString());
  }

  @Test
  public void testParseFileFailed() {
    input = new StringReader("q");
    stringBuffer.append("!!Enter initiateGame.\n!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n!!Enter setPet.\nSpecification file parse failed.\n");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController_error.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(stringBuffer.toString(), output.toString());
  }

  @Test
  public void testQuit() {
    input = new StringReader("q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append(
            "!!Enter setDoctorLucky.\n!!Enter setPet.\n!!Enter addPlayer.\n!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, ")
        .append("height=36, width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(stringBuffer.toString(), output.toString());
  }

  @Test
  public void testMovePlayer() {
    input = new StringReader("2 1 0 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 1\n")
        .append("** Choose a space to enter, input the index of space:\n").append("0. Armory\n")
        .append("6. Green House\n").append("15. Piazza\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter movePlayer.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter newTurn.\n").append("* After:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 1.Billiard Room; 6.Green House; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Revolver:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testMovePlayerAndInputWrong() {
    input = new StringReader("2 1 4 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 1\n")
        .append("** Choose a space to enter, input the index of space:\n").append("0. Armory\n")
        .append("6. Green House\n").append("15. Piazza\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("Invalid choice, choose again.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testPickUpThenSpaceNoItemLeft() {
    input = new StringReader("2 2 1 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 2\n")
        .append("** Choose an item to pick up, input the index of item:\n")
        .append("1. Loud Noise\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter pickUpItem.\n")
        .append("!!Enter newTurn.\n").append("!!Enter getPlayerByName.\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[Loud Noise],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[Loud Noise],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("2. Pick up an item: no item can be picked.\n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testPickAndReachMaxItems() {
    input = new StringReader("2 2 1 2 1 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 3.Dining Hall; 14.Parlor; 19.Wine Cellar; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Crepe Pan:3; Sharp Knife:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 2\n")
        .append("** Choose an item to pick up, input the index of item:\n").append("1. Crepe Pan\n")
        .append("2. Sharp Knife\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter pickUpItem.\n")
        .append("!!Enter newTurn.\n").append("!!Enter getPlayerByName.\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[Crepe Pan],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[Crepe Pan],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 3.Dining Hall; 14.Parlor; 19.Wine Cellar; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Sharp Knife:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 2\n")
        .append("** Choose an item to pick up, input the index of item:\n")
        .append("1. Sharp Knife\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter pickUpItem.\n")
        .append("!!Enter newTurn.\n").append("!!Enter getPlayerByName.\n")
        .append("Can not pick up more items.\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[Crepe Pan],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 2.Carriage House; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 3.Dining Hall\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.3 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[Crepe Pan],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 3.Dining Hall; 14.Parlor; 19.Wine Cellar; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Sharp Knife:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController_maxitems.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testPickAndInputWrong() {
    input = new StringReader("2 2 3 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 2\n")
        .append("** Choose an item to pick up, input the index of item:\n")
        .append("1. Loud Noise\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("Invalid choice, choose again.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.1 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testLookAroundAndPetInNeighbor() {
    input = new StringReader("2 3 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 3\n").append("!!Enter getAroundInfo.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("** 0. Armory\n").append("This space is invisible.\n").append("** 6. Green House\n")
        .append("Green House [index=6, neighbors=[0.Armory, 7.Hedge Maze],")
        .append(" items=[Trowel, Pinking Shears], players=[]]\n").append("** 15. Piazza\n")
        .append("Piazza [index=15, neighbors=[5.Foyer, 7.Hedge Maze, ")
        .append("20.Winter Garden], items=[Civil War Cannon], players=[]]\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testLookAroundAndPlayerInNeighbor() {
    input = new StringReader("2 3 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter addPlayer.\n")
        .append("!!Enter setMaxTurn.\n").append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=6, currentSpaceName=Green House]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human1's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 chose the option 3\n").append("!!Enter getAroundInfo.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("** 0. Armory\n").append("This space is invisible.\n").append("** 6. Green House\n")
        .append("Green House [index=6, neighbors=[0.Armory, 7.Hedge Maze]")
        .append(", items=[Trowel, Pinking Shears], players=[human2]]\n").append("** 15. Piazza\n")
        .append("Piazza [index=15, neighbors=[5.Foyer, 7.Hedge Maze,")
        .append(" 20.Winter Garden], items=[Civil War Cannon], players=[]]\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[]")
        .append(", currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human2's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=6, currentSpaceName=Green House]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Trowel:2; Pinking Shears:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController_playerInNeighbor.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testReachMaxTurnsWithComputer() {
    input = new StringReader("2 3");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter addPlayer.\n")
        .append("!!Enter setMaxTurn.\n").append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n")
        .append("robot [playerType=robot, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen, players=[robot]]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 3.Dining Hall; 14.Parlor; 19.Wine Cellar; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Crepe Pan:3; Sharp Knife:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 3\n").append("!!Enter getAroundInfo.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("** 3. Dining Hall\n").append("Dining Hall [index=3, neighbors=[1.Billiard Room, ")
        .append("4.Drawing Room, 8.Kitchen, 17.Tennessee Room], items=[], players=[]]\n")
        .append("** 14. Parlor\n").append("Parlor [index=14, neighbors=[8.Kitchen, ")
        .append("16.Servants' Quarters], items=[], players=[]]\n").append("** 19. Wine Cellar\n")
        .append("Wine Cellar [index=19, neighbors=[2.Carriage House,")
        .append(" 8.Kitchen, 20.Winter Garden], items=[Rat Poison, Piece of Rope], players=[]]\n")
        .append("* After:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen, players=[robot]]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----robot's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("robot [playerType=robot, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen, players=[human]]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 3.Dining Hall; 14.Parlor; 19.Wine Cellar; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Crepe Pan:3; Sharp Knife:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n").append("robot chose the option 3\n")
        .append("!!Enter getAroundInfo.\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter newTurn.\n").append("** 3. Dining Hall\n")
        .append("Dining Hall [index=3, neighbors=[1.Billiard Room, ")
        .append("4.Drawing Room, 8.Kitchen, 17.Tennessee Room], items=[], players=[]]\n")
        .append("** 14. Parlor\n").append("Parlor [index=14, neighbors=[8.Kitchen,")
        .append(" 16.Servants' Quarters], items=[], players=[]]\n").append("** 19. Wine Cellar\n")
        .append("Wine Cellar [index=19, neighbors=[2.Carriage House, ")
        .append("8.Kitchen, 20.Winter Garden], items=[Rat Poison, Piece of Rope], players=[]]\n")
        .append("* After:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("robot [playerType=robot, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=8, currentSpaceName=Kitchen, players=[human]]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 2.Carriage House; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 3.Dining Hall\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("\n")
        .append("***********************************\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Game Over! You have reached the maximum number of turns, Docotr has escaped.\n")
        .append("");
    rg = new RandomGenerator(2);
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, rg,
        "./res/WorldSpecification_testForController_robot.txt", "2");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testMovePet() {
    input = new StringReader("2 4 3 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 4\n").append("!!Enter getSpaceNumFromMansion.\n")
        .append("** Choose a space index[0-20]:\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("The pet has been moved into 3.Dining Hall\n").append("!!Enter movePet.\n")
        .append("!!Enter newTurn.\n").append("* After:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testMovePetAndInputWrong() {
    input = new StringReader("2 4 30 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter setMaxTurn.\n")
        .append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human chose the option 4\n").append("!!Enter getSpaceNumFromMansion.\n")
        .append("** Choose a space index[0-20]:\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("Invalid choice, choose again.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human's turn, No.1 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=7, currentSpaceName=Hedge Maze]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 0.Armory; 6.Green House; 15.Piazza; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Loud Noise:2; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testMakeAttemptFailed() {
    input = new StringReader("2 5 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter addPlayer.\n")
        .append("!!Enter setMaxTurn.\n").append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=50, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human1's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory, Doctor Lucky's health=50,")
        .append(" pet=Fortune the Cat, players=[human2]]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 1.Billiard Room; 6.Green House; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Revolver:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("5. Make an attempt\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("human1 chose the option 5\n")
        .append("!!Enter getItemsByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter makeAttempt.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter newTurn.\n").append("Attack Failed! You are seen by another player!\n")
        .append("* After:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory, players=[human2]]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 50\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human2's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=0, currentSpaceName=Armory, players=[human1]]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 1.Billiard Room; 6.Green House; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Revolver:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController_attemptfailed.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testMakeAttemptSuccessfullyWithItemAndGameOver() {
    input = new StringReader("2 2 1 3 5 1");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter addPlayer.\n")
        .append("!!Enter setMaxTurn.\n").append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=2, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=0, currentSpaceName=Armory]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human1's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[], ")
        .append("currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 19.Wine Cellar; 20.Winter Garden; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Chain Saw:4; Big Red Hammer:4; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 chose the option 2\n")
        .append("** Choose an item to pick up, input the index of item:\n").append("1. Chain Saw\n")
        .append("2. Big Red Hammer\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter pickUpItem.\n")
        .append("!!Enter newTurn.\n").append("!!Enter getPlayerByName.\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[Chain Saw],")
        .append(" currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 2\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human2's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 1.Billiard Room; 6.Green House; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Revolver:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 chose the option 3\n").append("!!Enter getAroundInfo.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("** 1. Billiard Room\n").append("This space is invisible.\n")
        .append("** 6. Green House\n")
        .append("Green House [index=6, neighbors=[0.Armory, 7.Hedge Maze],")
        .append(" items=[Trowel, Pinking Shears], players=[]]\n").append("** 7. Hedge Maze\n")
        .append("Hedge Maze [index=7, neighbors=[0.Armory, 6.Green House, 15.Piazza],")
        .append(" items=[Loud Noise], players=[]]\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 2.Carriage House; health is 2\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 3.Dining Hall\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human1's turn, No.3 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[Chain Saw],")
        .append(" currentSpaceIndex=2, currentSpaceName=Carriage House, Doctor Lucky's health=2]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 19.Wine Cellar; 20.Winter Garden; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Big Red Hammer:4; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("5. Make an attempt\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("human1 chose the option 5\n")
        .append("!!Enter getItemsByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("** Choose an item to use, input the index of item:\n")
        .append("!!Enter getItemsByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("1. Chain Saw; damage:4\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter makeAttempt.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter newTurn.\n")
        .append("Use Chain Saw, attack Successfully!\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 3.Dining Hall; health is 0\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 4.Drawing Room\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n").append("\n")
        .append("***********************************\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("Game Over! Doctor Lucky has been killed, Winner is human1\n").append("");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController_attemptsuccessfully.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

  @Test
  public void testMakeAttemptSuccessfullyWithoutItem() {
    input = new StringReader("2 3 3 5 q");
    stringBuffer.append("!!Enter initiateGame.\n").append("!!Enter setMansion.\n")
        .append("!!Enter setDoctorLucky.\n").append("!!Enter setPet.\n")
        .append("!!Enter addPlayer.\n").append("!!Enter addPlayer.\n")
        .append("!!Enter setMaxTurn.\n").append("***********************************\n")
        .append("Mansion created successfully, the information is as follows:\n")
        .append("-----Mansion Information-----\n").append("!!Enter getMansionInfo.\n")
        .append("Mansion [name=Doctor Lucky's Mansion, height=36,")
        .append(" width=30, spacesNum=21, itemsNum=20]\n")
        .append("-----Main Character Information-----\n").append("!!Enter getDoctorLuckyInfo.\n")
        .append("Doctor Lucky [health=2, currentSpaceIndex=0]\n")
        .append("-----Pet Information-----\n").append("!!Enter getPetInfo.\n")
        .append("Fortune the Cat [currentSpaceIndex=0]\n")
        .append("***********************************\n").append("Menu(Input 'q'/'Q' to quit):\n")
        .append("1. Create world map.\n").append("2. Start game.\n").append("\n")
        .append("***********************************\n").append("Game Start!\n").append("\n")
        .append("-----Players Information-----\n").append("!!Enter getPlayersInfo.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n").append("\n")
        .append("***********************************\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human1's turn, No.1 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 19.Wine Cellar; 20.Winter Garden; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Chain Saw:4; Big Red Hammer:4; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 chose the option 3\n").append("!!Enter getAroundInfo.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("** 19. Wine Cellar\n")
        .append("Wine Cellar [index=19, neighbors=[2.Carriage House, 8.Kitchen, 20.Winter Garden],")
        .append(" items=[Rat Poison, Piece of Rope], players=[]]\n")
        .append("** 20. Winter Garden\n")
        .append("Winter Garden [index=20, neighbors=[2.Carriage House, 15.Piazza, 19.Wine Cellar],")
        .append(" items=[], players=[]]\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[], currentSpaceIndex=2,")
        .append(" currentSpaceName=Carriage House]\n").append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 1.Billiard Room; health is 2\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 1.Billiard Room\n")
        .append("!!Enter getTurns.\n").append("!!Enter getMaxTurn.\n")
        .append("!!Enter getDoctorLuckyHealth.\n").append("!!Enter getTurns.\n")
        .append("!!Enter getPlayerNameByTurn.\n").append("!!Enter getTurns.\n").append("\n")
        .append("-----human2's turn, No.2 turn-----\n").append("* Before:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[], currentSpaceIndex=0,")
        .append(" currentSpaceName=Armory]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 1.Billiard Room; 6.Green House; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Revolver:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 chose the option 3\n").append("!!Enter getAroundInfo.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("** 1. Billiard Room\n").append("This space is invisible.\n")
        .append("** 6. Green House\n")
        .append("Green House [index=6, neighbors=[0.Armory, 7.Hedge Maze],")
        .append(" items=[Trowel, Pinking Shears], players=[]]\n").append("** 7. Hedge Maze\n")
        .append("Hedge Maze [index=7, neighbors=[0.Armory, 6.Green House, 15.Piazza],")
        .append(" items=[Loud Noise], players=[]]\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 2.Carriage House; health is 2\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 3.Dining Hall\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human1's turn, No.3 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[]")
        .append(
            ", currentSpaceIndex=2, currentSpaceName=Carriage House, Doctor Lucky's health=2]\n")
        .append("* Choose action:\n").append("!!Enter getCurrentSpaceIndexByPlayerName.\n")
        .append("!!Enter getPlayerByName.\n").append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("!!Enter getItemsBySpaceIndex.\n").append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 19.Wine Cellar; 20.Winter Garden; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Chain Saw:4; Big Red Hammer:4; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("5. Make an attempt\n").append("!!Enter gePlayerTypeByName.\n")
        .append("!!Enter getPlayerByName.\n").append("human1 chose the option 5\n")
        .append("!!Enter getItemsByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter makeAttempt.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter newTurn.\n")
        .append("Poke doctor's eyes, attack Successfully!\n").append("* After:\n")
        .append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human1 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=2, currentSpaceName=Carriage House]\n")
        .append("!!Enter getDoctorLuckyName.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter getSpaceNameByIndex.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("Doctor Lucky's current space is 3.Dining Hall; health is 1\n")
        .append("!!Enter getPetName.\n").append("!!Enter getPetCurrentSpaceIndex.\n")
        .append("!!Enter getPetCurrentSpaceIndex.\n").append("!!Enter getSpaceNameByIndex.\n")
        .append("Fortune the Cat's current space is 4.Drawing Room\n").append("!!Enter getTurns.\n")
        .append("!!Enter getMaxTurn.\n").append("!!Enter getDoctorLuckyHealth.\n")
        .append("!!Enter getTurns.\n").append("!!Enter getPlayerNameByTurn.\n")
        .append("!!Enter getTurns.\n").append("\n").append("-----human2's turn, No.4 turn-----\n")
        .append("* Before:\n").append("!!Enter getPlayerInfoByName.\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("human2 [playerType=human, maxItems=1, carriedItems=[],")
        .append(" currentSpaceIndex=0, currentSpaceName=Armory]\n").append("* Choose action:\n")
        .append("!!Enter getCurrentSpaceIndexByPlayerName.\n").append("!!Enter getPlayerByName.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("!!Enter getNeighborsInfoBySpaceIndex.\n")
        .append("!!Enter getNeighborsBySpaceIndex.\n")
        .append("1. Move to a neighboring space: 1.Billiard Room; 6.Green House; 7.Hedge Maze; \n")
        .append("!!Enter getItemsInfoBySpaceIndex.\n").append("!!Enter getItemsBySpaceIndex.\n")
        .append("2. Pick up an item: Revolver:3; \n").append("3. Look around\n")
        .append("4. Move the pet\n").append("!!Enter getDoctorLuckyCurrentSpaceIndex.\n")
        .append("!!Enter gePlayerTypeByName.\n").append("!!Enter getPlayerByName.\n")
        .append("Game Quit.");
    killDoctorLuckyController = new KillDoctorLuckyConsoleController(input, output, null,
        "./res/WorldSpecification_testForController_attemptsuccessfully.txt", "10");
    killDoctorLuckyController.setModel(killDoctorLucky);
    killDoctorLuckyController.playGame();
    assertEquals(output.toString(), stringBuffer.toString());
  }

}
